services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
    - fishcomp-manager

  backend:
    build: ./backend
    container_name: backend
    ports:
    - 81:81
    volumes:
      - ./backend:/var/www 
    networks:
      - fishcomp-manager

networks:
  fishcomp-manager:
    driver: bridge