services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: php
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "9000:9000"

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: fishcomp_manager
      POSTGRES_USER: user # Change this in production
      POSTGRES_PASSWORD: password # Use a stronger password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"