services:
  database:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      fishcomp-manager:
        ipv4_address: 172.21.0.4

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8088:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      fishcomp-manager:
        ipv4_address: 172.21.0.5
    depends_on:
      - database

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php-development:8.3
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    ports:
      - "8081:80"
    env_file: .env
    networks:
      fishcomp-manager:
        ipv4_address: 172.21.0.3

  frontend:
    image: php-development:8.3
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www
    networks:
      fishcomp-manager:
        ipv4_address: 172.21.0.2
    depends_on:
      - backend

networks:
  fishcomp-manager:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
      options:
        com.docker.network.bridge.enable_ip_masquerade: "false"